/**
 * Member C Configuration & Data Fixtures
 * For category: Mon chien (data list provided by team)
 */

export const memberCConfig = {
    id: 'c',
    name: 'Cửa hàng C',
    displayName: 'Món Chiên',
    description: 'Cửa hàng C chuyên phục vụ món chiên và thực đơn theo vùng miền',
    logo: '🍟',
    color: '#f97316',
    primaryCategory: 'MonChien',
    owner: 'Founder C',
    location: 'TP.HCM',
    phone: '+84 28 9999 6688',
    email: 'memberc@refood.vn',
    website: 'https://memberc.refood.vn',
    socialLinks: {
        facebook: 'https://facebook.com/memberc',
        instagram: 'https://instagram.com/memberc',
    },
}

/**
 * Member C Product Fixtures
 */
export const memberCProducts = [
    {
        id: 'c-prod-001',
        name: 'Trà sen Tây Hồ',
        description: 'Trà ướp hoa sen, thơm dịu, mang nét truyền thống Hà Nội.',
        category: 'MonChien',
        region: 'Bắc',
        price: 32000,
        imageUrl: 'https://images.unsplash.com/photo-1564894809611-1742fc40ed80?w=1200&q=80',
        stock: 50,
        rating: 4.8,
        reviews: 120,
        isActive: true,
    },
    {
        id: 'c-prod-002',
        name: 'Sấu ngâm',
        description: 'Chua ngọt, giải nhiệt mùa hè.',
        category: 'MonChien',
        region: 'Bắc',
        price: 28000,
        imageUrl: 'https://images.unsplash.com/photo-1513558161293-cdaf765ed2fd?w=1200&q=80',
        stock: 42,
        rating: 4.6,
        reviews: 94,
        isActive: true,
    },
    {
        id: 'c-prod-003',
        name: 'Chè đỗ đen',
        description: 'Vừa là chè vừa là thức uống mát.',
        category: 'MonChien',
        region: 'Bắc',
        price: 30000,
        imageUrl: 'https://images.unsplash.com/photo-1525385133512-2f3bdd039054?w=1200&q=80',
        stock: 36,
        rating: 4.7,
        reviews: 86,
        isActive: true,
    },
    {
        id: 'c-prod-004',
        name: 'Nước mơ ngâm',
        description: 'Vị chua thanh, hơi ngọt.',
        category: 'MonChien',
        region: 'Bắc',
        price: 26000,
        imageUrl: 'https://images.unsplash.com/photo-1461023058943-07fcbe16d735?w=1200&q=80',
        stock: 39,
        rating: 4.5,
        reviews: 75,
        isActive: true,
    },
    {
        id: 'c-prod-005',
        name: 'Trà hoa cúc',
        description: 'Thanh mát, giúp ngủ ngon.',
        category: 'MonChien',
        region: 'Bắc',
        price: 27000,
        imageUrl: 'https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?w=1200&q=80',
        stock: 46,
        rating: 4.7,
        reviews: 88,
        isActive: true,
    },
    {
        id: 'c-prod-006',
        name: 'Nước rau ngô',
        description: 'Thức uống dân dã, màu vàng trong, vị ngọt thanh tự nhiên.',
        category: 'MonChien',
        region: 'Bắc',
        price: 25000,
        imageUrl: 'https://images.unsplash.com/photo-1470337458703-46ad1756a187?w=1200&q=80',
        stock: 44,
        rating: 4.4,
        reviews: 69,
        isActive: true,
    },
    {
        id: 'c-prod-007',
        name: 'Sâm dứa',
        description: 'Mùi thơm đặc trưng, ngọt nhẹ.',
        category: 'MonChien',
        region: 'Trung',
        price: 30000,
        imageUrl: 'https://images.unsplash.com/photo-1517701550927-30cf4ba1f0d6?w=1200&q=80',
        stock: 41,
        rating: 4.7,
        reviews: 77,
        isActive: true,
    },
    {
        id: 'c-prod-008',
        name: 'Chè hạt sen',
        description: 'Bổ dưỡng, thường thấy ở Huế.',
        category: 'MonChien',
        region: 'Trung',
        price: 33000,
        imageUrl: 'https://images.unsplash.com/photo-1497935586351-b67a49e012bf?w=1200&q=80',
        stock: 35,
        rating: 4.8,
        reviews: 91,
        isActive: true,
    },
    {
        id: 'c-prod-009',
        name: 'Sữa đậu xanh rau má',
        description: 'Kết hợp vị béo ngậy của đậu xanh và sự thanh mát của rau má.',
        category: 'MonChien',
        region: 'Trung',
        price: 35000,
        imageUrl: 'https://images.unsplash.com/photo-1514995669114-6081e934b693?w=1200&q=80',
        stock: 38,
        rating: 4.9,
        reviews: 105,
        isActive: true,
    },
    {
        id: 'c-prod-010',
        name: 'Cà phê muối Huế',
        description: 'Lớp kem muối mặn béo béo trung hòa vị đắng của cà phê.',
        category: 'MonChien',
        region: 'Trung',
        price: 42000,
        imageUrl: 'https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?w=1200&q=80',
        stock: 40,
        rating: 4.9,
        reviews: 140,
        isActive: true,
    },
    {
        id: 'c-prod-011',
        name: 'Sữa hạt sen',
        description: 'Vị ngọt dịu, bùi bùi, béo thơm nhẹ và giúp an thần.',
        category: 'MonChien',
        region: 'Trung',
        price: 34000,
        imageUrl: 'https://images.unsplash.com/photo-1551024709-8f23befc6cf7?w=1200&q=80',
        stock: 33,
        rating: 4.6,
        reviews: 72,
        isActive: true,
    },
    {
        id: 'c-prod-012',
        name: 'Trà gừng',
        description: 'Cay ấm, hợp thời tiết mưa lạnh miền Trung.',
        category: 'MonChien',
        region: 'Trung',
        price: 29000,
        imageUrl: 'https://images.unsplash.com/photo-1515823662972-da6a2e4d3002?w=1200&q=80',
        stock: 45,
        rating: 4.5,
        reviews: 66,
        isActive: true,
    },
    {
        id: 'c-prod-013',
        name: 'Cà phê sữa đá Sài Gòn',
        description: 'Đậm đà vị cà phê robusta pha phin hòa quyện cùng sữa đặc.',
        category: 'MonChien',
        region: 'Nam',
        price: 39000,
        imageUrl: 'https://images.unsplash.com/photo-1445116572660-236099ec97a0?w=1200&q=80',
        stock: 58,
        rating: 4.9,
        reviews: 182,
        isActive: true,
    },
    {
        id: 'c-prod-014',
        name: 'Nước mía',
        description: 'Ngọt tự nhiên, cực kỳ phổ biến.',
        category: 'MonChien',
        region: 'Nam',
        price: 22000,
        imageUrl: 'https://images.unsplash.com/photo-1509042239860-f550ce710b93?w=1200&q=80',
        stock: 60,
        rating: 4.7,
        reviews: 126,
        isActive: true,
    },
    {
        id: 'c-prod-015',
        name: 'Trà tắc',
        description: 'Chua ngọt, rất dễ uống.',
        category: 'MonChien',
        region: 'Nam',
        price: 24000,
        imageUrl: 'https://images.unsplash.com/photo-1544145945-f90425340c7e?w=1200&q=80',
        stock: 54,
        rating: 4.6,
        reviews: 98,
        isActive: true,
    },
    {
        id: 'c-prod-016',
        name: 'Sinh tố bơ',
        description: 'Béo ngậy, đặc trưng miền nhiệt đới.',
        category: 'MonChien',
        region: 'Nam',
        price: 38000,
        imageUrl: 'https://images.unsplash.com/photo-1497534446932-c925b458314e?w=1200&q=80',
        stock: 48,
        rating: 4.8,
        reviews: 137,
        isActive: true,
    },
    {
        id: 'c-prod-017',
        name: 'Nước dừa',
        description: 'Tươi mát, đặc biệt nhiều ở miền Tây.',
        category: 'MonChien',
        region: 'Nam',
        price: 26000,
        imageUrl: 'https://images.unsplash.com/photo-1525385133512-2f3bdd039054?w=1200&q=80',
        stock: 52,
        rating: 4.7,
        reviews: 111,
        isActive: true,
    },
    {
        id: 'c-prod-018',
        name: 'Sữa bắp',
        description: 'Ngọt béo tự nhiên.',
        category: 'MonChien',
        region: 'Nam',
        price: 28000,
        imageUrl: 'https://images.unsplash.com/photo-1559839914-17aae19cec71?w=1200&q=80',
        stock: 43,
        rating: 4.6,
        reviews: 84,
        isActive: true,
    },
]

export const memberCStats = {
    totalProducts: 18,
    activeListings: 18,
    totalSales: 3600000,
    totalOrders: 242,
    averageRating: 4.7,
    totalReviews: 1821,
    memberSince: '2024-06-10',
    bestSeller: 'c-prod-013',
}
